# Generated by Django 5.0.6 on 2024-07-08 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='users',
        ),
        migrations.AddField(
            model_name='organisation',
            name='users',
            field=models.ManyToManyField(related_name='organisations', to=settings.AUTH_USER_MODEL),
        ),
    ]
