# Generated by Django 5.0.6 on 2024-07-08 20:45

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.CharField(default=user.models.generate_user_id, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
